language: node_js
node_js:
  - "11"
cache:
  directories:
    - node_modules
deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm publish"
  skip_cleanup: true
branches:
  only:
    - master
